config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # experiences with nested my_experiences
  resources :experiences do
    resources :my_experiences, only: [:new, :create]
    post :create_alt, on: :member
  end

  # my_experiences with nested reviews
  resources :my_experiences, only: [:index, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]

  # invitations(friends)
  resources :invitations, only: [:create, :destroy, :update]

  # custom routes
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as:'feed'
  get 'done/:id', to: 'my_experiences#done', as: 'done'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_beauty_search.html.erb
<%# <div class="search_div">
  <form action="">
    <input type="text" :query, params[:query], class="search_input" placeholder="Find an Experience">
    <button type="submit">
      <i class="fa-solid fa-magnifying-glass-location search_button"></i>
    </button>
  </form>
</div> %>
<div class="search_div">
  <%= simple_form_for experiences_path, method: :get do |f| %>

      <%= f.text_field :query %>

      <%= button_tag( :class => "search_button") do %>
        <i class="fa-solid fa-magnifying-glass-location"></i>
      <% end %>
  <% end %>
</div>

app/views/shared/_card_experience.html.erb
<div class="card card-experience">
  <% if experience.photo.attached? %>
    <%= cl_image_tag experience.photo.key, height: 302, width: 280,  crop: :fill, fetch_format: :png %>
  <% else %>
    <%= image_tag("placeholder_exp", width: 280, height: 302) %>
  <% end %>
  <div class="card-experience-infos">
    <div>
      <h1><%= link_to experience.name, experience_path(experience.id) %></h1>
      <h2><%= experience.city %>, <%= experience.country %></h2>
      <h3> #<%= experience.exp_type %></h3>
    </div>
    <div class="done">
      <%# <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          Done
        </label>
      </div> %>
    </div>

      <div class="card-experience-user avatar-bordered">
        <%= cl_image_tag experience.user.photo.key, height: 40, width: 40, radius: "max",  crop: :fill, fetch_format: :png %>
      </div>
      <%=  link_to  profile_path(id: experience.user.id) do %>
        <div class="card-experience-overlay"> </div>
      <% end %>


  </div>
</div>

app/views/shared/_card_feed.html.erb
<div class="card-feed">
  <div class="container">
    <div class="d-flex flex-row">
      <div class="row p-2">
        <div class="user-avatar">
        </div>
      </div>
      <div class="p-2 row">
        <p>User_name has done this</p>
        <p>Thursday, 8 September</p>
      </div>
    </div>
    <div class="row">
      <div class="experience-image">
    </div>
    <div class="row">
      <h1>Experience Name</h1>
      <h2></h2>
    </div>
    </div>
  </div>
</div>

<hr>

app/views/shared/_card_review_experience.html.erb
<div class="review">
  <div class="d-flex flex-row">
    <div class="row align-self-center"> <%= cl_image_tag review.user.photo.key, height: 40, width: 40, radius: "max",  crop: :fill, fetch_format: :png %> </div>
    <div class="p-2 row">
      <p> @<%= review.user.username %> </p>
      <p style="color: grey"> <%= review.user.city %> </p>
    </div>
  </div>
  <div class="row">
    <p> <%= review.rating %> ⭐️ </p>
    <p> "<%= review.content %>" </p>
    <div class="details pt-4 pb-2">
      <p> <%= review.created_at %> </p>
    </div>
    <div class="container p-2">
      <hr>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer-wagon <%= yield(:footer_class) %>

  <div class="row footer <%= yield(:footer_class) %>">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-6">
          <div class="footer-links align-middle">
            <a href="https://github.com/Jennacodes101/dejavu"><i class="fab fa-github"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>
        </div>
        <div class="col-6">
          <div class="footer-copyright">
            © DEJAVU 2022
          </div>
        </div>
      </div>
    </div>
  </div>

<%# </div> %>

app/views/shared/_info_window.html.erb
<div class="d-flex align-items-center flex-column">
    <div class="card-experience-user avatar-bordered">
      <%= cl_image_tag experience.user.photo.key, height: 40, width: 40, radius: "max",  crop: :fill, fetch_format: :png %>
    </div>
    <div>
      <h2><%= link_to experience.name, experience_path(experience.id) %></h2>
    </div>
    <div>
      <p><%= link_to experience.address, experience_path(experience.id) %></p>
    </div>
</div>

app/views/shared/_map.html.erb
<%# <div class="pb-20"> %>
<% @markers = @markers.map do |marker| %>
  <% marker[:avatar_url] = cl_image_path(marker[:image_url]) %>
  <% marker %>
<% end %>

<div style="width: 612px; height: 612px; border-radius: 16px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_map_show.html.erb
<%# <div class="pb-20"> %>
<% @markers = @markers.map do |marker| %>
  <% marker[:avatar_url] = cl_image_path(marker[:image_url]) %>
  <% marker %>
<% end %>

<div style="width: 636px; height: 612px; border-radius: 16px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar_dejavu.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-lewagon <%= yield(:navbar_class) %>">
  <div class="container">
    <div class="navbar-logo col-md-2">
      <div style="height: 48px; width:216 px">
        <%= link_to image_tag("LogoDejaVU3.png",alt: "LogoDejaVu" ), root_path, class: "dropdown-item" %>
      </div>
    </div>

    <div class="navbar-search d-flex col-md-4">
      <div class="form-search">
        <%= form_tag experiences_path, method: :get do %>
        <div class="row position-relative">
          <div class="col-12">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control border-dark bg-transparent text-dark rounded-pill pr-5",
              placeholder: "Find an Experience" %>
          </div>
          <div class="position-absolute" style="left:165px">
            <%= button_tag( class: "search_button", style: "border:none" ) do %>
              <i class="fa-solid fa-magnifying-glass-location"></i>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class="collapse navbar-collapse col-md-6" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <div class="m-2 nav-item">
            <div class="btn-explore">
                <%= link_to experiences_path do %>
                  <div class="d-flex flex-row p-1">
                    <div style="height:20px; width:20px; margin-right: 4px">
                      <%= image_tag("map-regular.svg",alt: "ExploreButton") %>
                    </div>
                    <div class="pl-2">
                      <span> Explore</span>
                    </div>
                  </div>
                <% end %>
            </div>
          </div>

          <li class="nav-item dropdown">
            <div class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, height: 44, width: 44, radius: "max",  crop: :fill, fetch_format: :png %>
              <% else %>
                <%= image_tag("user_avatar.png", class: "avatar") %>
              <% end %>
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "Feed", feed_path, class: "dropdown-item" %>
              <%# <%= link_to "Explore", experiences_path, class: "dropdown-item" %>
              <%= link_to "Profile", profile_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn-login" %>
          </li>
          <li class="nav-item">
            <%= link_to "Join", new_user_registration_path, class: "btn-join" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="form-search">
  <%= form_tag experiences_path, method: :get do %>
    <div class="row mt-4">
      <div class="col-11">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find an Experience" %>
      </div>
      <div class="col-1">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_search2.html.erb
<div class="row no-gutters mt-3 align-items-center">
  <div class="col col-md-4">
    <input class="form-control border-secondary rounded-pill pr-5" type="search" value="search" id="example-search-input2">
  </div>
  <div class="col-auto">
    <button class="btn btn-outline-light text-dark border-0 rounded-pill ml-n5" type="button">
      <i class="fa fa-search"></i>
    </button>
  </div>
</div>