config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # experiences with nested my_experiences
  resources :experiences do
    resources :my_experiences, only: [:new, :create]
    post :create_alt, on: :member
  end

  # my_experiences with nested reviews
  resources :my_experiences, only: [:index, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]

  # invitations(friends)
  resources :invitations, only: [:create, :destroy, :update]

  # custom routes
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as:'feed'
  get 'done/:id', to: 'my_experiences#done', as: 'done'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_friends_list_card.html.erb
<div class="ms-1">
  <!-- -->
  <% @friends.each do |friend| %>
    <div clas="friend-invite-card">
      <ul class="list-group list-group-horizontal">
        <%= link_to profile_path(friend.id) do %>
          <li>
            <% if friend.photo.attached?  %>
              <%= cl_image_tag friend.photo.key,
                height: 50, width: 50, crop: :fill, quality: 70,
              radius: :max, format: :png %>
            <% else %>
              <%= image_tag('user_avatar.png', class: 'friends-list-photo') %>
            <% end %>
          </li>
          <li>
            <p> <%= "#{friend.first_name} #{friend.last_name}" %></p>
          </li>
        <% end %>
        <li>
          <div class=" mt-2 ms-2 align-self-center text-end">
            <%= link_to "Remove", invitation_path(ids: {id1: current_user.id,
              id2: friend.id}), data: { confirm: "Are you
                sure you want to remove #{friend.first_name} #{friend.last_name}
              as a friend ?"}, method: :delete, class: "btn-friends-cancel-full"%>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/pages/_my_reviews_card.html.erb
<div class="container content">
  <% if @access == "owner" %>
      <h5 class="pt-1 text-muted bg-exp"> Your reviews: </h5>
    <% else %>
      <h5 class="pt-1 text-muted bg-exp"><%= "#{@profile_user.first_name}'s reviews" %></h5>
    <% end %>
    <div class="cards">
      <% @user_reviews.each do |review| %>
        <% exp = Experience.joins(:my_experiences, :reviews ).where('reviews.id' =>  review.id) %>
        <div class="review_profile_card m-2">
          <h5 class="m-2" ><%= exp.first.name %></h5>
          <div class="review p-2 m-2">
            <div class="d-flex flex-row">
              <% if @access == 'owner' %>
                <div class="row align-self-center"> <%= cl_image_tag current_user.photo.key, height: 40, width: 40, radius: "max",  crop: :fill, fetch_format: :png %> </div>
              <% else %>
                <div class="row align-self-center"> <%= cl_image_tag @profile_user.photo.key, height: 40, width: 40, radius: "max",  crop: :fill, fetch_format: :png %> </div>
              <% end %>
              <div class="p-2 row">
                <% if  @access == 'owner' %>
                  <p> @<%= @current_user.username %> </p>
                  <p style="color: grey"> <%= current_user.city %> </p>
                <% else %>
                  <p> @<%= @profile_user.username %> </p>
                  <p style="color: grey"> <%= @profile_user.city %> </p>
                <% end %>
              </div>
            </div>
            <div class="row">
              <p> <%= review.rating %> ⭐️ </p>
              <p> "<%= review.content %>" </p>
              <div class="details pt-4 pb-2">
                <p> <%= review.created_at %> </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/_requests_list_card.html.erb
<div class="p-1">
  <% @friend_invites.each do |invite|  %>
    <div class="friend-invite-card ">
    <!--if user created the friend request -->
      <%if @current_user.id == invite.user_id %>
        <% friend_info = User.find(invite.friend_id) %>
        <ul class="list-group list-group-horizontal ">
          <%= link_to profile_path(invite.friend_id) do  %>
            <li>
              <div class="ps-2 pt-1 ">
                <%= cl_image_tag friend_info.photo.key,
                  height: 50, width: 50, crop: :fill, quality: 70,
                  radius: :max, format: :png, :border=>"1px_solid_white"%>
              </div>
            </li>
            <li class="">
              <div class="">
                <p> <%= "#{friend_info.first_name} #{friend_info.last_name}" %></p>
              </div>
            </li>
          <% end %>
          <li class=" ps-3 align-content-center d-flex ">
            <div class="d-inline-flex align-self-center ">
              <p class="friend-card-request"> Requested✓ </p>
                <%= link_to "Cancel", invitation_path(ids: {id1: current_user.id,
                id2: invite.friend_id}), method: :delete, data: { confirm: "Are you sure you want to cancel your friend request to #{friend_info.first_name}
                #{friend_info.last_name} ?"},
                class: "btn-friends-cancel "%>
            </div>
          </li>
        </ul>


      <% else %>
        <!--if user was sent the friend request -->
        <% friend_info = User.find(invite.user_id) %>
        <ul class="list-group list-group-horizontal">
          <%= link_to profile_path(invite.user_id) do  %>
            <li>
              <div class="ps-2 pt-1 ">
                <% if friend_info.photo.attached?  %>
                  <%= cl_image_tag friend_info.photo.key,
                    height: 50, width: 50, crop: :fill, quality: 70,
                    radius: :max, format: :png, :border=>"1px_solid_white"%>
                <% else  %>
                  <%= image_tag('user_avatar.png', class: 'friends-list-photo') %>
                <% end %>
              </div>
            </li>
            <li class="">
              <p> <%= "#{friend_info.first_name} #{friend_info.last_name}" %></p>
            </li>
          <% end %>
          <li class=" ps-3 align-content-center d-flex ">
            <div class="d-inline-flex align-self-center ">
              <%= link_to "Accept", invitation_path(ids: {id1: current_user.id,
              id2: invite.user_id}), method: :patch, class: "btn-friends-accept "%>

              <%= link_to "Reject", invitation_path(ids: {id1: current_user.id,
              id2: invite.user_id}), method: :delete , data: { confirm: "
              Are you sure you want to cancel your friend request to #{friend_info.first_name}
              #{friend_info.last_name} ?"},
              class: "btn-friends-cancel "%>

            </div>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_user_card.html.erb
<div style="">
  <div class="text-center border-lifted mt-4 p-4">
    <div class="" >
      <% if current_user.photo.key == nil %>
        <%= image_tag("user_avatar",
        height: 80, width: 80, crop: :fill, quality: 70,
        radius: :max, format: :png) %>
      <% else %>
        <%= cl_image_tag @current_user.photo.key,
        height: 80, width: 80, crop: :fill, quality: 70,
        radius: :max, format: :png %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-6-lg col-12-sm">
        <div class="d-flex justify-content-center align-self-center">
          <h4 class="pt-2 pe-1" style="color: grey"> <%="#{current_user.first_name} #{current_user.last_name}"%> </h4>
          <h5 class="pt-2 ps-1 align-self-center"> @<%= current_user.username %> </h5>
        </div>
        <div>
          <button class="card-expand-btn" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseExample" aria-expanded="false"
            aria-controls="collapseExample" data-controller="profile">
          +
        </div>
      </div>
    </div>

    </button>

    <div class="collapse" id="collapseExample">
      <div class="p-2 text-center">
        <p class ="my-3"> <%= current_user.bio %> </p>
        <p class="mb-3"> <%= "Email: #{current_user.email}" %></p>
        <p class="mb-3"> <%= " #{current_user.city}" %></p>
        <p class="mb-3"> <%= "Birthday: #{current_user.birthday}" %></p>
        <%= link_to "...", edit_user_registration_path(@current_user),
          class: ""%>
      </div>
    </div>

    <div class="col-lg-3 col-md-3 col-sm-12">
      <ul class="profile-stats-list" >
        <li>
          <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
              <%= "#{@friends.count} friends" %>
            </button>
            <div class="dropdown-menu friends-list-nav" aria-labelledby="dropdownMenuClickableInside" style="min-width: 300px;">
              <div class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
                <div class="nav-item" role="presentation">
                  <button class="nav-link nav-pills active px-3" id="pills-friends-tab" data-bs-toggle="pill" data-bs-target="#pills-friends" type="button" role="tab" aria-controls="pills-friends" aria-selected="true">Friends</button>
                </div>
                <div class="vl ms-2 me-2">

                </div>
                <div class="nav-item" role="presentation">
                  <button class="nav-link nav-pills" id="pills-requests-tab" data-bs-toggle="pill" data-bs-target="#pills-requests" type="button" role="tab" aria-controls="pills-requests" aria-selected="false">Requests</button>
                </div>
              </div>
              <hr class="whitehr">

              <div class="tab-content" id="pills-tabContent">

                <div class="tab-pane fade show active" id="pills-friends" role="tabpanel" aria-labelledby="pills-friends-tab">
                  <%= render 'friends_list_card' %>
                </div>

                <div class="tab-pane fade" id="pills-requests" role="tabpanel" aria-labelledby="pills-requests-tab">
                  <%= render 'requests_list_card' %>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li> <%=link_to "#{@user_experiences.count} experiences", "#", class: "btn"%> </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/_user_dashboard.html.erb
<div class="border-lifted mt-4">
  <div class="p-4">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="experiences-tab" data-bs-toggle="tab" data-bs-target="#experiences-tab-pane" type="button" role="tab" aria-controls="experiences-tab-pane" aria-selected="true">Experiences</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="wishlist-tab" data-bs-toggle="tab" data-bs-target="#wishlist-tab-pane" type="button" role="tab" aria-controls="wishlist-tab-pane" aria-selected="false">Wishlist</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="done-tab" data-bs-toggle="tab" data-bs-target="#done-tab-pane" type="button" role="tab" aria-controls="done-tab-pane" aria-selected="false">Done</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews-tab-pane" type="button" role="tab" aria-controls="reviews-tab-pane" aria-selected="false" >Reviews</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="experiences-tab-pane" role="tabpanel" aria-labelledby="experiences-tab" tabindex="0">
        <%= render 'user_experiences' %>
      </div>
      <div class="tab-pane fade" id="wishlist-tab-pane" role="tabpanel" aria-labelledby="wishlist-tab" tabindex="0">
        <%= render 'user_wishlist' %>
      </div>
      <div class="tab-pane fade" id="done-tab-pane" role="tabpanel" aria-labelledby="done-tab" tabindex="0">
        <%= render 'user_done' %>
      </div>
      <div class="tab-pane fade" id="reviews-tab-pane" role="tabpanel" aria-labelledby="reviews-tab" tabindex="0">
        <%= render 'my_reviews_card.html.erb' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_user_done.html.erb
<div class="container"></div>
  <table class="table">
    <thead>
      <th> Experience </th>
      <th> Location </th>
      <th> Reviewed? </th>
    </thead>
    <tbody>
      <% @done_user_experiences.each do |my_experience| %>
        <tr>
          <%experience = Experience.find(my_experience.experience_id) %>
          <td> <%= experience.name %> </td>
          <td> <%= experience.address %> </td>
          <% review = Review.find_by(my_experience_id: my_experience.id)  %>
            <% if review.nil? %>
              <% if @access == 'owner' %>
                <td> <%=link_to "+ Review", experience_path(experience.id),
                  class: "rounded-pill btn btn-dark" %></td>
              <% else %>
                <td> Not yet! </td>
              <% end %>
            <% else  %>
              <td> ✓ </td>
            <% end %>
        </tr>
      <% end  %>
    </tbody>
  </table>
</div>

app/views/pages/_user_experiences.html.erb
<div class="container border-sunk">
  <div class="row my-1">
    <div class="container-fluid py-1">
      <div class="d-flex">
        <% if @access == 'owner'%>
          <h5 class="pt-1 text-muted bg-exp"> Your experiences: </h5>
        <% else %>
          <h5 class="pt-1 text-muted bg-exp"><%= "#{@profile_user.first_name}'s experiences" %></h5>
        <% end %>
      </div>
      <div class="d-flex flex-row flex-nowrap overflow-auto">
        <% @user_experiences.each do |experience| %>
          <div style="padding: 10px">
            <div class="card card-experience">
              <% if experience.photo.attached? %>
                <%= cl_image_tag experience.photo.key, height: 302, width: 280,  crop: :fill, fetch_format: :png %>
              <% else %>
                <%= image_tag("placeholder_exp.png", width: 280, height: 302) %>
              <% end  %>
              <div class="card-experience-infos">
                <div >
                  <h1><%= link_to experience.name, experience_path(experience.id) %></h1>
                  <h2><%= experience.city %>, <%= experience.country %></h2>
                  <h3> #<%= experience.exp_type %></h3>
                </div>
                <div class="card-experience-edit">
                  <%= link_to '...', edit_experience_path %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_user_visit_card.html.erb
\ <div class="text-center p-4 vstcard">
  <div class="d-flex flex-column justify-content-center align-self-center">

    <div class="row">
      <div class="vstuser-photo">
        <%= cl_image_tag @profile_user.photo.key,
          height: 80, width: 80, crop: :fill, quality: 100,
          radius: :max, format: :png%>
      </div>
    </div>

    <div class="row">
      <div class="col-6-lg col-12-sm">
        <div class="d-flex justify-content-center align-self-center">
          <h4 class="pt-2 pe-1" style="color: grey"> <%= @profile_user.first_name %> </h4>
          <h5 class="pt-2 ps-1 align-self-center"> @<%= @profile_user.username %> </h5>
        </div>
          <h6 class="ps-1" style="color: grey"> <%= @profile_user.city %> </h6>
        <div>
          <button class="card-expand-btn" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseExample" aria-expanded="false"
            aria-controls="collapseExample" data-controller="profile">
          +
        </div>
      </div>
    </div>

    </button>

      <div class="collapse" id="collapseExample">
        <div class="p-2 text-center">
          <p class ="my-3"> <%= @profile_user.bio %> </p>
          <p class="mb-3"> Email: <%= @profile_user.email %> </p>
          <p class="mb-3"> <%= @profile_user.city %> </p>
          <p class="mb-3"> Birthday: <%= @profile_user.birthday %> </p>
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <div class="p-2">
          <!--if user does not have a pending request or a accepted request -->
          <% if !Invitation.reacted?(current_user.id, @profile_user.id) %>
              <div class="">
                <%= link_to 'Add Friend',
                  invitations_path(ids: {id1: current_user.id, id2: @profile_user.id}),
                  class: "rounded-pill btn btn-primary btn-sm", method: :post
                %>
              </div>
            <!-- if user friendship is confirmed -->
            <% elsif Invitation.confirmed_record?(current_user.id, @profile_user.id)%>
              <div class="">
                <%= link_to 'Friends ✔', "#", class: "rounded-pill btn btn-outline-success btn-sm" %>
              </div>
            <!-- User friendship is pending -->
            <% else %>
              <div class="">
                <% pending_invite = Invitation.find_invitation(current_user.id, @profile_user.id) %>
              </div>
              <% if pending_invite.id == current_user.id %>
                <div class="">
                  <%= link_to "Accept Friend Request",
                    invitation_path(ids: {id1: current_user.id, id2: @profile_user.id}),
                    class: "rounded-pill btn btn-outline-success btn-sm", method: :patch %>
                </div>
              <% else %>
                <div class="">
                  <%= link_to 'Pending Request', "#", class: "rounded-pill btn btn-outline-secondary disabled btn-sm" %>
                </div>
              <% end %>
            <% end %>
        </div>

        <div class="p-2 vstr-card-footer">
          <% if Invitation.confirmed_record?(current_user.id, @profile_user.id)%>
            <%= link_to 'Remove as friend', invitation_path(ids: {id1: current_user.id,
              id2: @profile_user.id}), method: :delete, data: { confirm: 'Are you sure?' },
              class: "rounded-pill btn btn-outline-danger btn-sm" %>
          <% elsif Invitation.pending_record?(current_user.id, @profile_user.id) %>
            <%= link_to 'Cancel Request', invitation_path(ids: {id1: current_user.id,
              id2: @profile_user.id}), method: :delete, data: { confirm: 'Are you sure?' },
              class: "rounded-pill btn btn-outline-danger btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_user_wishlist.html.erb
<div class="pb-2">
  <div class="row my-1">
    <div class="container-fluid py-1">
      <div class="d-flex">
        <% if @access == "owner" %>
          <h5 class="pt-1 text-muted bg-exp"> Your wishlist: </h5>
        <% else %>
          <h5 class="pt-1 text-muted bg-exp"><%= "#{@profile_user.first_name}'s wishlist" %></h5>
        <% end %>
      </div>
      <div class="cards-lg">
        <% @user_experiences_wishlist.each do |exp| %>
            <div class="wishlist-card" >
              <div class="card text-bg-light">
                <%= cl_image_tag exp.photo.key, height: 150, width: 500, crop: :fill,
                  :transformation => {:effect => "blur:300"}, :effect=>"brightness:-25", class: "card-img"%>
                <div class="card-img-overlay text-center">
                  <h5 class="my-3"> <%=link_to "#{exp.name}", experience_path(exp.id), class: "wishlist-card-title" %> </h5>
                  <% if @access == 'owner' %>
                    <% my_exp = MyExperience.find_by(user_id: current_user.id, experience_id: exp.id) %>
                      <div class="done-btn"> <%= link_to "done", done_path(my_exp.id),  class: "rounded-pill btn btn-sm btn-outline-light"%></div>
                      <% %>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/feed.html.erb
<div class="container">
  <h1>Feed</h1>
  <div class="row">
    <div class="col-6">
      <div class="row">
        <%= render 'shared/card_feed' %>
      </div>
    </div>
    <div class="col-6">
      <div class="map">
        <%= render 'shared/map' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>

<div class="banner d-flex">
  <div class="container m-auto">
    <div class="cover d-flex align-items-center justify-content-center">
      <div class="text-center">
        <div class="banner-container-phrases" style="height: 50px">
          <h4> <span data-controller="typed-js"></span> </h4>
        </div>
        <div>
          <div class="banner-letters">
            <%= link_to image_tag("DejaVU.png",alt: "DejaVu" ), experiences_path, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for(:footer_class, "footer-home") %>

app/views/pages/profile.html.erb
<div style="margin-top: 80px; margin-bottom: 24px">
  <div class="container">
    <%# <%= @access %>
    <% current_user.id %>
      <% if @access == 'owner' %>
        <%# <div class="row py-3 text-center">
          <h1>  Your Profile  </h1>
        </div> %>
        <div class="row">
          <%= render 'user_card' %>
        </div>
        <div class="">
          <%= render 'user_dashboard' %>
        </div>
      <% else  %>
        <div class="row pt-2 text-muted">
          <h6> <%= "#{@profile_user.first_name}'s profile" %></h6>
        </div>
        <div class="row">
          <div class="col-3-lg col-3-md col-12-sm">
            <%= render "user_visit_card" %>
          </div>
          <div class="col-3-lg col-3-md col-12-sm">
            <%# <%= render 'user_experiences' %>
            <%= render 'user_dashboard' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>