config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # experiences with nested my_experiences
  resources :experiences do
    resources :my_experiences, only: [:new, :create]
    post :create_alt, on: :member
  end

  # my_experiences with nested reviews
  resources :my_experiences, only: [:index, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]

  # invitations(friends)
  resources :invitations, only: [:create, :destroy, :update]

  # custom routes
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get 'feed', to: 'pages#feed', as:'feed'
  get 'done/:id', to: 'my_experiences#done', as: 'done'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/experience.rb
class Experience < ApplicationRecord

  #--VALIDATIONS--
  validates :name, presence: true
  # validates :description, presence: true
  # validates :image, presence: true
  validates :exp_type, presence: true
  validates :country, presence: true
  validates :city, presence:true
  validates :address, presence:true
  # validates :contact, presence: true
  # validates :url, presence: true
  # validates :price, presence: true

  #--DATABASE--
  belongs_to :user
  has_many :my_experiences
  has_many :reviews, through: :my_experiences
  has_one_attached :photo


  #--Geocoding--
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # pgSearch
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :description, :address, :contact, :price, :exp_type, :country, :city, :contact ],
    associated_against: {
      user: [ :email, :first_name, :last_name, :username, :birthday, :city, :bio, :phone_number ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  before_action :find_experience, only: [:show, :edit, :update, :destroy, :create_review, :create_alt]


  def index
    # Start Geocoding
    @experiences = Experience.geocoded
    @experiences = policy_scope(Experience)

    # Start PgSearch
    if params[:query].present?
      @experiences = Experience.global_search(params[:query])
    end
    geo_map

    # End PgSearch
  end

  def show
    @my_experience = MyExperience.find_by(experience: @experience, user: current_user)
    @review = Review.find_by(my_experience_id: @my_experience.id) unless @my_experience.nil?
    geo_map2(@experience)
  end

  def new
    @experience = Experience.new
    @exp_types = ['museum','food', 'landmark', 'nightlife', 'nature','classes', 'outdoor activity', 'service', 'excursion']
    authorize @experience
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    authorize @experience
    if @experience.save
      redirect_to experience_path(@experience), notice: 'Experience was successfully created.'
    else
      render :new
    end
  end

  def create_alt
    @my_experience = MyExperience.new(done: false , user_id: current_user.id, experience_id: params[:id] )
    if @my_experience.save
      redirect_to profile_path(current_user.id), notice: 'My_Experience was successfully created.'
    end
  end

  def edit; end

  def update
    @experience.update(experience_params)
    authorize @experience
    redirect_to experience_path(@experience)
  end


  def destroy
    @experience.destroy
    redirect_to experiences_path
  end

  private

  def find_experience
    @experience = Experience.find(params[:id])
    authorize @experience
  end

  def experience_params
    params.require(:experience).permit(:name, :description, :image, :exp_type, :country, :city, :address, :contact, :url, :price, :photo)
  end

  def geo_map

    @markers = @experiences.geocoded.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { experience: experience }),
        image_url: experience.user.photo.key
        # image_url: Cloudinary::Utils.cloudinary_url(experience.user.photo.key)
      }
    end
  end

  def geo_map2(experience)

   @markers = [
      {
        lat: experience.latitude,
        lng: experience.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { experience: experience }),
        # image_url: Cloudinary::Utils.cloudinary_url(experience.user.photo.key)
        image_url: experience.user.photo.key
      }
    ]
  end
end

app/views/experiences/_form.html.erb
<%= simple_form_for experience do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :exp_type, collection: @exp_types, prompt: 'Choose an experience type', label:' Experience type' %>
  <%= f.input :country, as: :string %>
  <%= f.input :city %>


  <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>

  <p> Optional: </p>
  <%= f.input :photo, as: :file, required: false %>

  <%= f.button :submit, class: "rounded-pill btn btn-dark shadow-sm" %>

<% end %>

app/views/experiences/_formexperience.html.erb
<%= simple_form_for experience do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :exp_type %>
  <%= f.input :subtype %>
  <%= f.input :country, as: :string %>
  <%= f.input :city %>
  <%= f.input :address %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/experiences/_info_window.html.erb
<h2><%= experience.name %></h2>
<p><%= experience.address %></p>

app/views/experiences/_info_window2.html.erb
<h2><%= experience.name %></h2>
<p><%= experience.address %></p>

app/views/experiences/edit.html.erb
<div style="margin-top: 60px; margin-bottom: 30px">
  <div class="container">
    <div class="row justify-content-center pt-5">

      <div class="col-6 p-4 info info-border">
        <h3>Edit your Experience</h3>
        <hr>
        <%= render "form", experience: @experience %>
      </div>

    </div>
  </div>
</div>

app/views/experiences/index.html.erb
<div class="screen">
  <div class="container pt-4">
    <div class="col-12 p-4 create-exp">
      <%= link_to '+ Experience', new_experience_path, class:"btn btn-outline-dark border-1 rounded-pill shadow-sm" %>
    </div>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-6 p-3">
          <div class="cards index-cards"> <%# grid of cards %>
            <% @experiences.each do |experience|%>
              <%= render 'shared/card_experience', experience: experience %>
            <% end %>
          </div>
        </div>
        <div class="col-6 p-3">
          <div id="map">
            <%= render 'shared/map' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div style="margin-top: 60px; margin-bottom: 30px">
  <div class="container">
    <div class="row justify-content-center pt-5">
      <div class="col-6 p-4 info info-border">
        <h3> Create your Experience </h3>
        <hr>
        <%= render "form", experience: @experience %>
      </div>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<!-- For open graph meta tags -->
<% content_for :meta_title, "#{@experience.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @experience.description %>
<% if @experience.photo.attached? %>
  <% content_for :meta_image, cl_image_path(@experience.photo.key) %>
<% end %>
<!--  -->

<div class="screen">
  <div class="container">
    <div class="row pt-4 show-container">
      <div class="p-4 info info-border">
        <div class="container">
          <div class="row">
              <div class="col-6 overflow-auto" style="height: 612px">
                <div class="row">
                  <div class="col-8">
                    <div class="d-flex justify-content-between">
                      <div class="p-1">
                        <div style="height:20px; width:20px">
                          <%= link_to image_tag("circle-chevron-left-solid.svg",alt: "BackButton" ), experiences_path, class: "dropdown-item" %>
                        </div>
                      </div>
                      <div class="experience-name">
                        <h2> <%= @experience.name %> </h2>
                        <p> <%= @experience.city %>, <%= @experience.country %> </p>
                      </div>
                      <div class="m-8">
                        <% if policy(@experience).edit? %>
                          <%= link_to '...', edit_experience_path %>
                          <%# <%= link_to 'delete', experience_path(@experience), method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="col-4 pt-2">
                    <div class="d-flex flex-row-reverse">
                      <div class="experience-buttons">
                        <% unless !@my_experience.nil? %>
                          <%= link_to '+ Wishlist', create_alt_experience_path(@experience.id), method: :post, class:"btn-wishlist" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="image">
                    <% if @experience.photo.attached? %>
                      <%= cl_image_tag @experience.photo.key, crop: :fill, width: 400, height: 300, quality: 70, radius: 20, format: :png %>
                    <% else  %>
                      <%= image_tag("placeholder_exp", width: 400, height: 300) %>
                    <% end %>
                  </div>
                </div>

                <div class="row">
                  <div class="experience-infos">
                    <h6> " <%= @experience.description %> " </h6>
                    <p> <strong>Address:</strong> <%= @experience.address %> </p>
                    <p> <strong>Contact:</strong> <%= @experience.contact %> </p>
                    <p> <%= @experience.url %> </p>
                  </div>
                </div>
                <div class="inner">
                  <div class="d-flex justify-content-between pb-2">
                    <div class="align-self-center">
                      <h5>Reviews:</h5>
                    </div>
                    <div class="">
                      <% unless @my_experience.nil? %>
                        <%= link_to '+ Review', new_my_experience_review_path(@my_experience.id), class:"btn-review" %>
                      <% end %>
                    </div>
                  </div>
                  <div style="margin:0">
                    <hr>
                  </div>
                  <div class="container">
                    <div class="row">
                      <% @experience.reviews.each do |review| %>
                        <%= render 'shared/card_review_experience', review: review %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

            <div class="col-6 p-0">
              <div class="map-show">
                <%= render 'shared/map_show' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>